const Data: Array<any> = [
  {
    popularity: 269.003,
    vote_count: 2430,
    video: false,
    poster_path: '/mb7wQv0adK3kjOUr9n93mANHhPJ.jpg',
    id: 583083,
    adult: false,
    backdrop_path: '/wO5QSWZPBT71gMLvrRex0bVc0V9.jpg',
    original_language: 'en',
    original_title: 'The Kissing Booth 2',
    genre_ids: [35, 10749],
    title: 'The Kissing Booth 2',
    vote_average: 8.2,
    overview:
      'With college decisions looming, Elle juggles her long-distance romance with Noah, changing relationship with bestie Lee and feelings for a new classmate.',
    release_date: '2020-07-24',
  },
  {
    popularity: 172.535,
    id: 300671,
    video: false,
    vote_count: 2039,
    vote_average: 7.1,
    title: '13 Hours: The Secret Soldiers of Benghazi',
    release_date: '2016-01-13',
    original_language: 'en',
    original_title: '13 Hours: The Secret Soldiers of Benghazi',
    genre_ids: [28, 36, 53],
    backdrop_path: '/ayDMYGUNVvXS76wQgFwTiUIDNb5.jpg',
    adult: false,
    overview:
      'An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.',
    poster_path: '/4qnEeVPM8Yn5dIVC4k4yyjrUXeR.jpg',
  },
  {
    popularity: 157.261,
    id: 516486,
    video: false,
    vote_count: 687,
    vote_average: 7.6,
    title: 'Greyhound',
    release_date: '2020-07-10',
    original_language: 'en',
    original_title: 'Greyhound',
    genre_ids: [10752, 28, 18],
    backdrop_path: '/xXBnM6uSTk6qqCf0SRZKXcga9Ba.jpg',
    adult: false,
    overview:
      'A first-time captain leads a convoy of allied ships carrying thousands of soldiers across the treacherous waters of the “Black Pit” to the front lines of WW2. With no air cover protection for 5 days, the captain and his convoy must battle the surrounding enemy Nazi U-boats in order to give the allies a chance to win the war.',
    poster_path: '/kjMbDciooTbJPofVXgAoFjfX8Of.jpg',
  },
  {
    popularity: 133.348,
    id: 547016,
    video: false,
    vote_count: 1418,
    vote_average: 7.4,
    title: 'The Old Guard',
    release_date: '2020-07-10',
    original_language: 'en',
    original_title: 'The Old Guard',
    genre_ids: [28, 14],
    backdrop_path: '/m0ObOaJBerZ3Unc74l471ar8Iiy.jpg',
    adult: false,
    overview:
      "Four undying warriors who've secretly protected humanity for centuries become targeted for their mysterious powers just as they discover a new immortal.",
    poster_path: '/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg',
  },
  {
    popularity: 120.918,
    vote_count: 5056,
    video: false,
    poster_path: '/7Dktk2ST6aL8h9Oe5rpk903VLhx.jpg',
    id: 454983,
    adult: false,
    backdrop_path: '/itiz2OBK4ns6XT0ufXtusojmMt9.jpg',
    original_language: 'en',
    original_title: 'The Kissing Booth',
    genre_ids: [35, 10749],
    title: 'The Kissing Booth',
    vote_average: 7.3,
    overview:
      "When teenager Elle's first kiss leads to a forbidden romance with the hottest boy in high school, she risks her relationship with her best friend.",
    release_date: '2018-05-11',
  },
  {
    popularity: 109.354,
    vote_count: 12166,
    video: false,
    poster_path: '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
    id: 313369,
    adult: false,
    backdrop_path: '/qJeU7KM4nT2C1WpOrwPcSDGFUWE.jpg',
    original_language: 'en',
    original_title: 'La La Land',
    genre_ids: [35, 18, 10402, 10749],
    title: 'La La Land',
    vote_average: 7.9,
    overview:
      'Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.',
    release_date: '2016-11-29',
  },
  {
    popularity: 104.9,
    vote_count: 125,
    video: false,
    poster_path: '/1hVEsBS4vnozB1yAsMiqW0IMxyp.jpg',
    id: 430155,
    adult: false,
    backdrop_path: '/6kJKTKnnPbpyeqCgodqgjkI9aMk.jpg',
    original_language: 'ru',
    original_title: 'Koma',
    genre_ids: [28, 14, 878],
    title: 'Coma',
    vote_average: 6.2,
    overview:
      'A young and talented architect comes to his senses after a horrific accident only to find himself in the odd dystopian world. A world that is filled with the memories of all current coma patients. Just like a human memory this world is fragmental, chaotic and unstable. This is COMA: icecaps, rivers and cities can all exist in a space of a single room and laws of physics are no longer laws as they can be bent.',
    release_date: '2019-11-19',
  },
  {
    popularity: 103.361,
    vote_count: 14029,
    video: false,
    poster_path: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    id: 475557,
    adult: false,
    backdrop_path: '/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
    original_language: 'en',
    original_title: 'Joker',
    genre_ids: [80, 18, 53],
    title: 'Joker',
    vote_average: 8.2,
    overview:
      'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
    release_date: '2019-10-02',
  },
  {
    popularity: 101.95,
    vote_count: 272,
    video: false,
    poster_path: '/jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg',
    id: 385103,
    adult: false,
    backdrop_path: '/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg',
    original_language: 'en',
    original_title: 'Scoob!',
    genre_ids: [12, 16, 35, 9648, 10751],
    title: 'Scoob!',
    vote_average: 7.8,
    overview:
      'In Scooby-Doo’s greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global “dogpocalypse,” the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.',
    release_date: '2020-07-08',
  },
  {
    popularity: 101.591,
    vote_count: 4230,
    video: false,
    poster_path: '/vPYgvd2MwHlxTamAOjwVQp4qs1W.jpg',
    id: 561,
    adult: false,
    backdrop_path: '/tIG8FwHRiHLOlWJdizp2oxdkSL2.jpg',
    original_language: 'en',
    original_title: 'Constantine',
    genre_ids: [18, 14, 27],
    title: 'Constantine',
    vote_average: 6.9,
    overview:
      'John Constantine has literally been to Hell and back. When he teams up with a policewoman to solve the mysterious suicide of her twin sister, their investigation takes them through the world of demons and angels that exists beneath the landscape of contemporary Los Angeles.',
    release_date: '2005-02-08',
  },
  {
    popularity: 99.709,
    vote_count: 19109,
    video: false,
    poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    id: 299536,
    adult: false,
    backdrop_path: '/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg',
    original_language: 'en',
    original_title: 'Avengers: Infinity War',
    genre_ids: [28, 12, 878],
    title: 'Avengers: Infinity War',
    vote_average: 8.3,
    overview:
      'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
    release_date: '2018-04-25',
  },
  {
    popularity: 92.275,
    vote_count: 23191,
    video: false,
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    id: 157336,
    adult: false,
    backdrop_path: '/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
    original_language: 'en',
    original_title: 'Interstellar',
    genre_ids: [12, 18, 878],
    title: 'Interstellar',
    vote_average: 8.3,
    overview:
      'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    release_date: '2014-11-05',
  },
  {
    popularity: 91.938,
    vote_count: 5249,
    video: false,
    poster_path: '/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg',
    id: 495764,
    adult: false,
    backdrop_path: '/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg',
    original_language: 'en',
    original_title:
      'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
    genre_ids: [28, 35, 80, 18],
    title:
      'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
    vote_average: 7.2,
    overview:
      'Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.',
    release_date: '2020-02-05',
  },
  {
    popularity: 91.445,
    vote_count: 47,
    video: false,
    poster_path: '/A11Ez4UkOE4Ysmtmur5Bho8qrGM.jpg',
    id: 611395,
    adult: false,
    backdrop_path: '/cAfW4ZPsLA6yOapJUSUq3fruCfQ.jpg',
    original_language: 'zh',
    original_title: '征途',
    genre_ids: [28, 12],
    title: 'Double World',
    vote_average: 7,
    overview:
      'Keen to bring honor to his clan, young villager Dong Yilong embarks on a perilous journey to compete in a tournament that selects warriors for battle.',
    release_date: '2019-11-22',
  },
  {
    popularity: 91.403,
    id: 35588,
    video: false,
    vote_count: 101,
    vote_average: 6,
    title: 'Geronimo: An American Legend',
    release_date: '1993-12-10',
    original_language: 'en',
    original_title: 'Geronimo: An American Legend',
    genre_ids: [36, 37],
    backdrop_path: '/6YSj3paJAn3p6F6cyfSdgLncFTQ.jpg',
    adult: false,
    overview:
      'The Apache Indians have reluctantly agreed to settle on a US Government approved reservation. Not all the Apaches are able to adapt to the life of corn farmers. One in particular, Geronimo, is restless. Pushed over the edge by broken promises and necessary actions by the government, Geronimo and thirty or so other warriors form an attack team which humiliates the government by evading capture, whi',
    poster_path: '/rmbeg5wHVjC68G00SKQ0xZQpZru.jpg',
  },
  {
    popularity: 89.267,
    vote_count: 4017,
    video: false,
    poster_path: '/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg',
    id: 419704,
    adult: false,
    backdrop_path: '/AeDS2MKGFy6QcjgWbJBde0Ga6Hd.jpg',
    original_language: 'en',
    original_title: 'Ad Astra',
    genre_ids: [18, 878],
    title: 'Ad Astra',
    vote_average: 6.1,
    overview:
      'The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.',
    release_date: '2019-09-17',
  },
  {
    popularity: 87.636,
    vote_count: 5334,
    video: false,
    poster_path: '/db32LaOibwEliAmSL2jjDF6oDdj.jpg',
    id: 181812,
    adult: false,
    backdrop_path: '/SPkEiZGxq5aHWQ2Zw7AITwSEo2.jpg',
    original_language: 'en',
    original_title: 'Star Wars: The Rise of Skywalker',
    genre_ids: [28, 12, 878],
    title: 'Star Wars: The Rise of Skywalker',
    vote_average: 6.6,
    overview:
      'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.',
    release_date: '2019-12-18',
  },
  {
    popularity: 86.86,
    vote_count: 26616,
    video: false,
    poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    id: 27205,
    adult: false,
    backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    original_language: 'en',
    original_title: 'Inception',
    genre_ids: [28, 12, 878],
    title: 'Inception',
    vote_average: 8.3,
    overview:
      'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    release_date: '2010-07-15',
  },
  {
    popularity: 86.46,
    vote_count: 8577,
    video: false,
    poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    id: 496243,
    adult: false,
    backdrop_path: '/ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg',
    original_language: 'ko',
    original_title: '기생충',
    genre_ids: [35, 18, 53],
    title: 'Parasite',
    vote_average: 8.5,
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    release_date: '2019-05-30',
  },
  {
    popularity: 84.438,
    vote_count: 44,
    video: false,
    poster_path: '/3ynPnBXQVT2Y0s19fDIPlWKUlxH.jpg',
    id: 587496,
    adult: false,
    backdrop_path: '/2gBMBfmQvHeOQQ5PiKiuxVdGs77.jpg',
    original_language: 'en',
    original_title: 'The Rental',
    genre_ids: [27, 53],
    title: 'The Rental',
    vote_average: 5.5,
    overview:
      'Two couples on an oceanside getaway grow suspicious that the host of their seemingly perfect rental house may be spying on them. Before long, what should have been a celebratory weekend trip turns into something far more sinister.',
    release_date: '2020-07-23',
  },
];
export default Data;
